# Generated by Django 4.2.16 on 2024-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
